# .github/workflows/pre-merge.yml
name: Pre-Merge Checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          
      - name: Run linting
        run: flake8 . --count --max-line-length=120 --statistics
        
      - name: Run tests
        run: pytest tests/
